[feature]支持线程信息展示和线程切换
Co-authored-by: zjw22<zhujiawei29@huawei.com>



# message auto-generated for no-merge-commit merge:
!63 merge zjw_thread into master

[feature]支持线程信息展示和线程切换

Created-by: zjw22
Commit-by: zjw22
Merged-by: ascend-robot
Description: ### 1. 修改描述
- **修改原因：支持simt里面的线程展示当前断在哪个线程里面。支持线程切换.  修改线程切换R寄存器读取问题。
- **修改方案：新增ascend info threads，和ascend thread <thread_idx>命令的解析和处理。
- **修改内容：lldb侧CommandObjectAscend.cpp新增对ascend info thread和ascend thread命令的解析和处理。以及ProcessGDBRemote.cpp获取warp信息。lldb server新增解析warp命令并通过DeviceContext的接口获取warp信息并返回。在AscendProcessLinux里面对stop信息进行判断，如果线程是活跃的，那么执行单步的时候，不改变当前的线程id。
- [ ] **涉及代码双合**(贴上另一个PR链接)：NA
----

### 2. 功能验证
- [x] **功能自验截图**（请确保不体现个人信息）  

```
(msdebug) r
[Launch of Kernel vec_add on Device 0]
1 location added to breakpoint 1
Process 2546536 stopped
[Switching to focus on Kernel vec_add, CoreId 0, Type aiv, Thread (0, 0, 0)]
* thread #1, name = 'test.fatbin', stop reason = breakpoint 1.2
    frame #0: 0x0000120044400478 device_debugdata_0`void SimtCompute<unsigned int>(dst=<unavailable>, src0=<unavailable>, src1=<unavailable>) (.vector) at kernel.cpp:10:15
   7    template <typename T>
   8    __simt_vf__ __aicore__ LAUNCH_BOUND(2048) inline void SimtCompute(__gm__ T *dst, __gm__ T *src0, __gm__ T *src1)
   9    {
-> 10       int idx = Simt::GetThreadIdx<0>();
   11       int blockIdx = Simt::GetBlockIdx();
   12       int tmp = 10;
   13       for (int i = idx; i < idx + 1; ++i) {
(msdebug) ascend thread 1
[Switching to focus on Kernel vec_add, CoreId 0, Type aiv, Thread (1, 0, 0)]
* thread #1, name = 'test.fatbin', stop reason = breakpoint 1.2
    frame #0: 0x0000120044400478 device_debugdata_0`void SimtCompute<unsigned int>(dst=<unavailable>, src0=<unavailable>, src1=<unavailable>) (.vector) at kernel.cpp:10:15
   7    template <typename T>
   8    __simt_vf__ __aicore__ LAUNCH_BOUND(2048) inline void SimtCompute(__gm__ T *dst, __gm__ T *src0, __gm__ T *src1)
   9    {
-> 10       int idx = Simt::GetThreadIdx<0>();
   11       int blockIdx = Simt::GetBlockIdx();
   12       int tmp = 10;
   13       for (int i = idx; i < idx + 1; ++i) {
(msdebug) ascend info threads
  PC                Thread
* 0x120044400478    (1,0,0)

(msdebug) n
Process 2546536 stopped
[Switching to focus on Kernel vec_add, CoreId 0, Type aiv, Thread (1, 0, 0)]
* thread #1, name = 'test.fatbin', stop reason = step over
    frame #0: 0x00001200444001d8 device_debugdata_0`int AscendC::Simt::GetThreadIdx<0>() (.vector) at kernel_simt_common_intf_impl.h:37:12
   34   template <int32_t dim>
   35   __aicore__ inline int32_t GetThreadIdx()
   36   {
-> 37       return GetThreadIdxImpl<dim>();
   38   }
   39  
   40   __aicore__ inline int32_t GetBlockIdx()
(msdebug) ascend thread 511
[Switching to focus on Kernel vec_add, CoreId 0, Type aiv, Thread (511, 0, 0)]
* thread #1, name = 'test.fatbin', stop reason = step over
    frame #0: 0x00001200444001d8 device_debugdata_0`int AscendC::Simt::GetThreadIdx<0>() (.vector) at kernel_simt_common_intf_impl.h:37:12
   34   template <int32_t dim>
   35   __aicore__ inline int32_t GetThreadIdx()
   36   {
-> 37       return GetThreadIdxImpl<dim>();
   38   }
   39  
   40   __aicore__ inline int32_t GetBlockIdx()
(msdebug) ascend thread 512
error: input thread is invalid and exceeds the value range indicated by thread_dim.
(msdebug) ascend info threads
  PC                Thread
* 0x1200444001d8    (511,0,0)

(msdebug) n
Process 2546536 stopped
[Switching to focus on Kernel vec_add, CoreId 0, Type aiv, Thread (511, 0, 0)]
* thread #1, name = 'test.fatbin', stop reason = step over
    frame #0: 0x00001200444002c8 device_debugdata_0`int AscendC::Simt::GetThreadIdxImpl<0>() (.vector) at kernel_simt_common_impl.h:76:16
   73       }
   74   #else
   75       if constexpr (dim == 0) {
-> 76           return __cce_simt_get_TID_X();
   77       }
   78       if constexpr (dim == 1) {
   79           return __cce_simt_get_TID_Y();
(msdebug) ascend info threads
  PC                Thread
* 0x1200444002c8    (511,0,0)


```
- [x] **冒烟是否通过** 

    失败用例与本pr无关，符合预期
![image.png](https://raw.gitcode.com/user-images/assets/8858745/b798d6aa-0495-4a83-b58a-a9f8739cf045/image.png 'image.png')
----

### 3. 代码检视
- **要求：**
  - 合入功能代码大于 200 行，需要sig会议申报代码检视议题，并在PR中标注会议。
  - committer评估是否需要在sig会议进行代码检视。
  - 参与检视的committer人员名单与检视时间。
  - 大于 1000 行代码原则上不允许合入，需进行备案。
- [x] **是否经过代码检视**  
- [x] **是否具备UT测试用例看护**
- [] **是否需要在sig会议中进行代码检视**: NA
- **检视committer人员名单与检视时间：**: NA
----
### 4. 资料修改自检
- **资料修改：**    
----

See merge request: Ascend/msdebug!63